[package]
name = "journal"
version = "0.1.0"
authors = ["Andre Ambrosio Boechat <boechat107@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
chrono = "0.4.11"
